//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentTests.NISTDataSets
{
    using System;
    using System.Collections.Generic;
    
    public class Standard
    {
        public long StandardID { get; set; }
        public string Description { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> MaxCapacity { get; set; }
        public string Nist { get; set; }
        public Nullable<long> StandardTypeID { get; set; }
        public string ModelNumber { get; set; }
        public Nullable<decimal> MaxUncertainty { get; set; }
        public string CertDescription { get; set; }
        public Nullable<System.DateTime> DateCalibrated { get; set; }
        public Nullable<System.DateTime> CalibrationDueDate { get; set; }
        public Nullable<decimal> Slope { get; set; }
        public Nullable<decimal> Intercept { get; set; }
    }
}
